name: client_flutter
description: Flutter client for GrandStack

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

  graphql_flutter: ^5.0.0
  graphql: ^5.0.0
  provider: ^6.0.1
  json_annotation: ^4.1.0
  smooth_star_rating: ^1.1.1
  flutter_animation_progress_bar: ^2.0.1
  progress_indicators: ^1.0.0
  json_helpers: ^0.1.5
  flutter_svg: ^0.23.0+1
  marquee: ^2.2.0
  hovering: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  json_serializable: ^5.0.2

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/images/matrix_specs.png

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icons/grandstack_icon.png'
